apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-backup-storage-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/mediatriple/videoonlystorage/cdn-platforms-and-videoonly2-db-backups/
    type: DirectoryOrCreate
